#
# NPMP  Nginx Php Mysql Phpmyadmin
#
# ███████████████████████████████████████████████████████████████
# █─▄▄▄▄██▀▄─██▄─█─▄█▄─▄███▄─█─▄████▀▄─██▄─█─▄█─▄▄─█▄─██─▄█▄─▄─▀█
# █▄▄▄▄─██─▀─███─▄▀███─██▀██▄─▄█████─▀─███▄─▄██─██─██─██─███─▄─▀█
# ▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▀▄▄▀▄▄▄▄▄▀▀▄▄▄▀▀▀▀▄▄▀▄▄▀▀▄▄▄▀▀▄▄▄▄▀▀▄▄▄▄▀▀▄▄▄▄▀▀
#
#
# https://github.com/saklyayoub
# +216 20 666 996
# saklyayoub@gmail.com
# 2021(R)
#
#
#

version: '3'

services: 

  mysql: 
    container_name: "${NGINX_HOST}_mysql"
    env_file: 
      - .env
    image: "mysql:${MYSQL_VERSION}"
    volumes: 
      - "/web/mysql:/var/lib/mysql"
    environment: 
#      - "TZ=${TZ}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
#      - "MYSQL_USER=${MYSQL_USER}"
#      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    logging: 
      driver: "${LOGIGIN_DRIVER}"
    restart: unless-stopped
    network_mode: bridge

  web:
    env_file: 
      - .env
    image: "nginx:latest" 
    container_name: "${NGINX_HOST}_web"
    volumes: 
      - "./web:/web"
      - "./etc/ssl:/etc/ssl"
      - "./etc/nginx/nginx.${NGINX_PROTOCOLE}.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - mysql
      - php
    environment: 
      NGINX_HOST: ${NGINX_HOST}
      TZ: ${TZ}
      VIRTUAL_HOST: ${NGINX_HOST}
    logging: 
      driver: "${LOGIGIN_DRIVER}"
    restart: unless-stopped
    network_mode: bridge

  php:
    env_file: 
      - .env 
    build: 
      context: ./docker
      dockerfile: "Dockerfile-${DOCKERFILE_VERSION}"
    container_name: "${NGINX_HOST}_php"
    environment: 
      TZ: "${TZ}"
    links:
      - mysql
    volumes: 
      - "./web:/web"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    logging: 
      driver: "${LOGIGIN_DRIVER}"
    restart: unless-stopped
    network_mode: bridge

  phpmyadmin:
    env_file: 
      - .env
    image: phpmyadmin 
    container_name: "${NGINX_HOST}_phpmyadmin"    
    environment: 
      TZ: ${TZ}
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MAX_EXECUTION_TIME: ${PMA_MAX_EXECUTION_TIME}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
      MEMORY_LIMIT: ${PMA_MEMORY_LIMIT}
      VIRTUAL_HOST: ${NGINX_HOST} 
    links:
      - mysql
    logging: 
      driver: "${LOGIGIN_DRIVER}"
    restart: unless-stopped
    network_mode: bridge

  composer:
    env_file: 
      - .env
    image: composer
    container_name: "${NGINX_HOST}_composer" 
    command: install
    volumes: 
      - "./web/app:/app"
    links:
      - mysql
    logging: 
      driver: "${LOGIGIN_DRIVER}"
    network_mode: bridge
